name: flutter_flame_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.33.0
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  flame_forge2d: ^0.19.2+1
  flame_audio: ^2.11.11
  flame_texturepacker: ^5.0.2
  oxygen: ^0.3.1
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/sprite_sheets/
    - assets/audio/
